### ISSUE TITLE
Position Fixed don't work in children elements

### ISSUE THREAD

**Issue by Chukwu3meka** [morellodev/react-awesome-reveal#157]
When using Fade component, any child component under fade with position: fixed doesn't work

**To Reproduce**
```jsx
import { Fade } from "react-awesome-reveal";

const Comp = () => 
    <main style={{ display: loading ? "none" : "unset" }}>
      <Fade direction="down" duration={2000}>
        {component}
      </Fade>
    </main>

export default Comp
```
> style for component
```scss

  & > div:first-of-type {
    position: fixed;
    width: 100%;
    height: 500px;
    bottom: 0;
    left: 0;
    right: 0;
  }

```

**Expected behavior**

Fixed position is not meant to scroll

 - Browser [Chrome]

**Additional context**

[Fixed position issue](https://stackoverflow.com/questions/16879737/position-fixed-is-not-working)
